syn match LedgerKeyword "￥"
syn match LedgerKeyword "include"
syn region Comment start=";"  end="\n"
syn region Comment start="*" end="\n" skip="*" 
syn region Comment start="comment" end="end comment"
syn match LedgerAccountKeyword ":"
